# version: '3.8'
# services: 
#   db:
#     image: postgres
#     restart: always
#     environment: 
#       - POSTGRES_USER: ${DATABASE_USER}
#       - POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#       - POSTGRES_DB: ${DB_NAME}
#     container_name: postgres-db
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data
#   nestjs:
#     build: 
#       context: .
#       dockerfile: ./Dockerfile
#     image: rakeem/nest-and-postgres-application:latest
#     environment: 
#       - DB_TYPE: ${DB_TYPE}
#       - POSTGRES_HOST: ${POSTGRES_HOST}
#       - POSTGRES_USER: ${DATABASE_USER}
#       - POSTGRES_PASS: ${DATABASE_PASSWORD}
#       - POSTGRES_DB: ${DB_NAME}
#       - POSTGRES_SYNC: false
#       - POSTGRES_PORT: ${POSTGRES_PORT}
#       - APP_PORT: ${APP_PORT}
#     ports: 
#       - "3000:3000" # expose-to-the-world : only-in-the-docker
#     container_name: vehicle-booking-container
#     depends_on: 
#       - db
#     volumes: 
#       - .:/app
#       - /app/node_modules
#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     container_name: nest-pgadmin4
#     environment: 
#       - PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#       - PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#       - PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
#     ports: 
#       - "5050:80"
#     volumes: 
#       - ./pgadmin-data:/var/lib/pgadmin
#     depends_on: 
#       - db
# volumes:
#   pgdata:
#   pgadmin-data:


version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-demo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - DB_TYPE${DB_TYPE}
      - POSTGRES_HOST${POSTGRES_HOST}
      - POSTGRES_USER${DATABASE_USER}
      - POSTGRES_PASS${DATABASE_PASSWORD}
      - POSTGRES_DB${DB_NAME}
      - POSTGRES_SYNCfalse
      - POSTGRES_PORT${POSTGRES_PORT}
      - APP_PORT${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      # - app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4-demo
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - '8080:80'
    depends_on:
      - db

# networks:
#     nestjs_network:
#       driver: bridge